# Generated by Django 5.2 on 2025-05-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatposte',
            name='status',
            field=models.CharField(choices=[('en cours de planification', 'En cours de planification'), ('planifié', 'Planifié'), ('refusé', 'Refusé')], default='en cours de planification', max_length=30),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='candidat_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='my_app.candidatposte'),
        ),
    ]
