# Generated by Django 5.2.6 on 2025-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_entretien_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('manager', 'Manager'), ('participant', 'Participant')], default='participant', max_length=15),
        ),
    ]
