# =============================================================================
# CONFIGURATION DJANGO - INTERVIEWPRO
# =============================================================================
# Ce fichier contient toutes les configurations de l'application Django
# Il définit les paramètres de base de données, sécurité, applications, etc.

"""
Django settings for projet_django project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# =============================================================================
# CONFIGURATION DES CHEMINS
# =============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR pointe vers le répertoire racine du projet Django
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# CONFIGURATION DE SÉCURITÉ
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# Clé secrète pour le chiffrement des sessions et cookies
# IMPORTANT : À changer en production !
SECRET_KEY = config('SECRET_KEY', default='cle-de-developpement-a-changer')

# SECURITY WARNING: don't run with debug turned on in production!
# Mode debug : affiche les erreurs détaillées (développement uniquement)
DEBUG = config('DEBUG', default=True, cast=bool)

# Hôtes autorisés à accéder à l'application
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# =============================================================================
# CONFIGURATION DU MODÈLE UTILISATEUR PERSONNALISÉ
# =============================================================================

# Utilisation de notre modèle User personnalisé au lieu du modèle par défaut
AUTH_USER_MODEL = 'my_app.User'

# =============================================================================
# CONFIGURATION DES APPLICATIONS DJANGO
# =============================================================================

# Application definition
# Liste des applications Django installées dans le projet
INSTALLED_APPS = [
    'my_app',                           # Notre application principale InterViewPro
    'django.contrib.admin',             # Interface d'administration Django
    'django.contrib.auth',              # Système d'authentification Django
    'django.contrib.contenttypes',      # Framework de types de contenu
    'django.contrib.sessions',          # Gestion des sessions utilisateur
    'django.contrib.messages',          # Système de messages flash
    'django.contrib.staticfiles',       # Gestion des fichiers statiques (CSS, JS, images)
]

# =============================================================================
# CONFIGURATION DES MIDDLEWARES
# =============================================================================

# Middleware : composants qui traitent les requêtes/réponses
# Ordre important : chaque middleware traite la requête dans l'ordre défini
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',        # Sécurité générale
    'django.contrib.sessions.middleware.SessionMiddleware', # Gestion des sessions
    'django.middleware.common.CommonMiddleware',            # Fonctionnalités communes
    'django.middleware.csrf.CsrfViewMiddleware',            # Protection CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Authentification
    'django.contrib.messages.middleware.MessageMiddleware',  # Messages flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Protection clickjacking
]

# =============================================================================
# CONFIGURATION DU ROUTAGE
# =============================================================================

# Configuration des URLs principales du projet
ROOT_URLCONF = 'projet_django.urls'

# =============================================================================
# CONFIGURATION DES TEMPLATES
# =============================================================================

# Configuration du moteur de templates Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Moteur Django
        'DIRS': [],                                                    # Dossiers de templates supplémentaires
        'APP_DIRS': True,                                              # Recherche dans les dossiers templates des apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',         # Objet request disponible dans tous les templates
                'django.contrib.auth.context_processors.auth',         # Objet user disponible dans tous les templates
                'django.contrib.messages.context_processors.messages', # Messages flash disponibles dans tous les templates
            ],
        },
    },
]

# =============================================================================
# CONFIGURATION WSGI
# =============================================================================

# Configuration du serveur WSGI pour le déploiement
WSGI_APPLICATION = 'projet_django.wsgi.application'

# =============================================================================
# CONFIGURATION DE LA BASE DE DONNÉES SQLITE
# =============================================================================

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Moteur SQLite
        'NAME': BASE_DIR / 'db.sqlite3',         # Chemin vers le fichier de base de données
    }
}

# =============================================================================
# CONFIGURATION DE L'AUTHENTIFICATION
# =============================================================================

# URLs de redirection pour l'authentification
LOGIN_URL = 'login'                    # URL de connexion (redirection si non connecté)
LOGIN_REDIRECT_URL = 'home'            # URL de redirection après connexion
LOGOUT_REDIRECT_URL = 'login'          # URL de redirection après déconnexion

# =============================================================================
# VALIDATION DES MOTS DE PASSE
# =============================================================================

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Validateurs de sécurité pour les mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Pas trop similaire aux infos utilisateur
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',            # Longueur minimale
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',           # Pas de mots de passe courants
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',          # Pas uniquement numérique
    },
]

# =============================================================================
# CONFIGURATION INTERNATIONALE
# =============================================================================

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'    # Langue par défaut (anglais)
TIME_ZONE = 'UTC'          # Fuseau horaire UTC
USE_I18N = True            # Activation de l'internationalisation
USE_TZ = True              # Utilisation des fuseaux horaires

# =============================================================================
# CONFIGURATION DES FICHIERS STATIQUES
# =============================================================================

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'     # URL de base pour les fichiers statiques

# =============================================================================
# CONFIGURATION DES CLÉS PRIMAIRES
# =============================================================================

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Type de clé primaire par défaut


# =============================================================================
# CONFIGURATION DES FICHIERS MÉDIA
# =============================================================================

# Configuration pour les fichiers uploadés par les utilisateurs (images, documents)
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Dossier de stockage des fichiers média
MEDIA_URL = '/media/'                          # URL de base pour accéder aux fichiers média

# =============================================================================
# CONFIGURATION EMAIL - ENVOI AUTOMATIQUE
# =============================================================================

# Configuration SMTP pour l'envoi d'emails automatiques
# Utilisé pour les notifications d'entretiens planifiés
# Les identifiants sont lus dans le fichier .env (jamais écrits dans le code).
# Sans identifiants, les e-mails s'affichent simplement dans la console.
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'    # Envoi réel via Gmail
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Affichage dans la console

EMAIL_HOST = 'smtp.gmail.com'                                  # Serveur SMTP Gmail
EMAIL_PORT = 587                                              # Port SMTP sécurisé
EMAIL_USE_TLS = True                                          # Chiffrement TLS activé

DEFAULT_FROM_EMAIL = f'InterViewPro <{EMAIL_HOST_USER or "noreply@interviewpro.local"}>'